# AutoGrad

**From Pytorch Docs :**

* `autograd` is central to all neural networks pytorch.

* The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

* While backpropogation computed ouput in neural network is sent back and gradients computed are updated 

* primary dtype in pytorch is `torch.Tensor`

In [0]:
import torch

`requires_grad` = used when back propogation is required for every tensor.

`.backward` = to initiate backpropogation

`.grad` = all gradient are accumulateed in this attribute

`.grad_fn` = show which operation were done to a tensor. ex: add, multiplication or division.

`.detach` = to get new tensor without gradient

In [31]:
# lets create a initial tensor to test all the above functions

x = torch.ones(3,3, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


Notice that `requires_grad=True` in output, that means we can do any operation to this tensor and do back propogation to that tensor.

In [32]:
# now lets do a addition operation to that base tensor

y = x + 2
print(y)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)


Now, Notice that `grad_fn` shows that addition operation has been.

In [33]:
# lets do more mathematical operation and see `grad_fn` results
z = y * y * 3
out = z.mean()

print(z)
print(out)

tensor([[27., 27., 27.],
        [27., 27., 27.],
        [27., 27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


Notice that we get grad_fn as multiplication and mean for both the operations we did on the tensor.

now these operations can be back propogated

In [34]:
out

tensor(27., grad_fn=<MeanBackward0>)

as you can see out contains a single scalar, lets do backprop to this

In [35]:
# to do backprop we just need to call .backward
out.backward()
# all the gradients accumulated are stored in a attribute called `.grad`
print(x.grad)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [46]:
# lets create a tensor with a requires_grad
x = torch.randn(3,3, requires_grad=True)
print(x)

# suppose we want to get that tensor with no grad_fn, then we can use detach() to get that tensor seperately
y = x.detach()
print(y)

tensor([[ 0.0672, -0.6789,  0.5611],
        [-0.3981,  0.2087,  0.6432],
        [-0.3187,  1.7171, -0.8935]], requires_grad=True)
tensor([[ 0.0672, -0.6789,  0.5611],
        [-0.3981,  0.2087,  0.6432],
        [-0.3187,  1.7171, -0.8935]])


Notice that y doesn't have `requires_grad` function. 

now that tensor can be used seperately for anyother functions.

In [21]:
# suppose we initiate a tensor without grad condition i.e `requires_grad=True`
a = torch.randn(2,2)

a = ((a-3)/(a-1))
print(a.requires_grad)

# we can use inplace function in pytorch to replace that to be True like this
# in pytorch any method followed by _ is used to replace original value
a.requires_grad_(True)
print(a.requires_grad)

# lets test if grad_fn shows up on any mathematical operations.
b = (a*a).sum()
print(f"grad_fn test : {b.grad_fn}")
print("yay!! now grad function is added")

False
True
grad_fn test : <SumBackward0 object at 0x7f96f85a8208>
yay!! now grad function is added
