<a href="https://colab.research.google.com/github/aravindh1293/pytorch_tensor_basics-handson/blob/master/pytorch_Tensors_Handson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [2]:
torch.cuda.is_available()

True

In [4]:
print0(torch.rand(2,2))

tensor([[0.4251, 0.4293],
        [0.1838, 0.1087]])


In [6]:
torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Tensors are normally said as `Ranked Matrices`.

scalar (single digit number array) is `rank 0`

vector (single digit number array) is `rank 1`

Multi Dimensional array is `rank 3` and so on



# Mathematical Operation on TENSORS

In [10]:
torch.rand(2,1) / torch.rand(1,2)

tensor([[0.5409, 0.8276],
        [0.8247, 1.2617]])

In [9]:
torch.tensor([2,1]).device

device(type='cpu')

In [0]:
torch.tensor([2,1]).to("cuda").device

## Tensor operations

In [14]:
a = torch.rand(3,3);a

tensor([[0.4512, 0.2817, 0.8710],
        [0.5605, 0.3482, 0.4778],
        [0.1833, 0.5551, 0.8936]])

In [15]:
a.max()

tensor(0.8936)

In [16]:
a.argmax()

tensor(8)

In [17]:
a.max().item()

0.8936260938644409

In [0]:
#same function with trailing _ is used to save memmory
rand_tensor = torch.rand(5,5)

In [31]:
%time rand_tensor.log2()

CPU times: user 114 µs, sys: 18 µs, total: 132 µs
Wall time: 688 µs


tensor([[-0.6864, -2.0273, -1.1626, -0.2683, -2.1208],
        [-0.2954, -0.4223, -1.9163, -0.4687, -1.3816],
        [-4.4537, -0.5819, -0.6029, -0.4917, -0.3268],
        [-0.7446, -0.3050, -2.6243, -0.2757, -0.4811],
        [-0.0819, -1.3161, -3.0947, -0.6724, -1.1464]])

In [32]:
%time rand_tensor.log2_()

CPU times: user 134 µs, sys: 0 ns, total: 134 µs
Wall time: 106 µs


tensor([[-0.6864, -2.0273, -1.1626, -0.2683, -2.1208],
        [-0.2954, -0.4223, -1.9163, -0.4687, -1.3816],
        [-4.4537, -0.5819, -0.6029, -0.4917, -0.3268],
        [-0.7446, -0.3050, -2.6243, -0.2757, -0.4811],
        [-0.0819, -1.3161, -3.0947, -0.6724, -1.1464]])

## tensor reshaping

In [33]:
tensor = torch.rand(784); tensor

tensor([0.6431, 0.5259, 0.6138, 0.0405, 0.1835, 0.5611, 0.0561, 0.9500, 0.5390,
        0.1343, 0.0072, 0.8464, 0.8515, 0.9668, 0.4035, 0.6110, 0.5899, 0.6836,
        0.8519, 0.2937, 0.2328, 0.6203, 0.4701, 0.1285, 0.3617, 0.8525, 0.4432,
        0.7820, 0.3017, 0.9664, 0.9380, 0.2520, 0.7416, 0.4429, 0.0680, 0.9141,
        0.7705, 0.7587, 0.3531, 0.5670, 0.2992, 0.5500, 0.9886, 0.2578, 0.3043,
        0.1770, 0.4854, 0.7671, 0.0879, 0.3487, 0.5162, 0.1095, 0.0630, 0.5722,
        0.4763, 0.6723, 0.7009, 0.3310, 0.2553, 0.6367, 0.0534, 0.2866, 0.7690,
        0.2431, 0.3542, 0.1695, 0.9589, 0.3224, 0.1134, 0.7363, 0.5259, 0.6883,
        0.9737, 0.3385, 0.4433, 0.1326, 0.7158, 0.5023, 0.9388, 0.4551, 0.3148,
        0.0488, 0.0362, 0.2464, 0.6740, 0.0988, 0.3929, 0.8166, 0.9262, 0.1860,
        0.9790, 0.1607, 0.4477, 0.1674, 0.7473, 0.8510, 0.0065, 0.5650, 0.6475,
        0.0982, 0.8903, 0.1088, 0.8507, 0.4030, 0.2072, 0.3270, 0.8890, 0.6732,
        0.0145, 0.7121, 0.8410, 0.3889, 

In [36]:
viewed_tensor = tensor.view(1,28,28); viewed_tensor

tensor([[[0.6431, 0.5259, 0.6138, 0.0405, 0.1835, 0.5611, 0.0561, 0.9500,
          0.5390, 0.1343, 0.0072, 0.8464, 0.8515, 0.9668, 0.4035, 0.6110,
          0.5899, 0.6836, 0.8519, 0.2937, 0.2328, 0.6203, 0.4701, 0.1285,
          0.3617, 0.8525, 0.4432, 0.7820],
         [0.3017, 0.9664, 0.9380, 0.2520, 0.7416, 0.4429, 0.0680, 0.9141,
          0.7705, 0.7587, 0.3531, 0.5670, 0.2992, 0.5500, 0.9886, 0.2578,
          0.3043, 0.1770, 0.4854, 0.7671, 0.0879, 0.3487, 0.5162, 0.1095,
          0.0630, 0.5722, 0.4763, 0.6723],
         [0.7009, 0.3310, 0.2553, 0.6367, 0.0534, 0.2866, 0.7690, 0.2431,
          0.3542, 0.1695, 0.9589, 0.3224, 0.1134, 0.7363, 0.5259, 0.6883,
          0.9737, 0.3385, 0.4433, 0.1326, 0.7158, 0.5023, 0.9388, 0.4551,
          0.3148, 0.0488, 0.0362, 0.2464],
         [0.6740, 0.0988, 0.3929, 0.8166, 0.9262, 0.1860, 0.9790, 0.1607,
          0.4477, 0.1674, 0.7473, 0.8510, 0.0065, 0.5650, 0.6475, 0.0982,
          0.8903, 0.1088, 0.8507, 0.4030, 0.2072, 0.3270,

In [37]:
 viewed_tensor.shape

torch.Size([1, 28, 28])

In [38]:
reshaped_tensor = tensor.reshape(1,28,28); reshaped_tensor.shape

torch.Size([1, 28, 28])

it is always advisable to use `.reshape` instead of `.view`.

## pytorch's Image type operations

In [0]:
image = torch.rand(600,400,3)

In [40]:
image.shape

torch.Size([600, 400, 3])

images are generaaly stored in computer as `[height, width, channels]`. but pytorch operates in `[channels, height, width]`

In [41]:
pytorch_image = image.permute(2,0,1); pytorch_image.shape

torch.Size([3, 600, 400])

## Tensor Numerical dtypes

In [0]:
long_tensor = torch.tensor([[1,2,3],[4,5,6]])

In [20]:
long_tensor.type()

'torch.LongTensor'

In [0]:
float_tensor = long_tensor.to(dtype=torch.float32)

In [24]:
float_tensor.type()

'torch.FloatTensor'