# Pytorch

* to run deep learning in GPU.
* it can do everything numpy does

In [0]:
# torch library
import torch

In [0]:
# it fills matrices with previous valuesstored in ram
torch.empty(3,3)

tensor([[1.6185e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45]])

In [0]:
# random numbers are generated
torch.rand(3,3)

tensor([[0.4436, 0.2200, 0.3861],
        [0.2348, 0.1917, 0.1985],
        [0.7635, 0.8923, 0.1314]])

In [0]:
#zero filled matrix
torch.zeros(3,3,dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [0]:
# create a tensor array
torch.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

In [0]:
x= torch.zeros(5,3);x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [0]:
# random normalised number like x
torch.randn_like(x)

tensor([[ 0.4548, -0.9514, -0.7825],
        [ 0.0859,  0.3853,  1.5086],
        [ 0.1250, -0.3386, -0.4915],
        [ 0.8515, -0.1364,  0.8045],
        [-0.4427,  0.2653, -0.0725]])

In [0]:
# to know dimension of a matrix
x.size()

torch.Size([5, 3])

## Addition In Multiple ways with Pytorch

In [0]:
x = torch.rand(2,3)
y = torch.rand(2,3)
x+y

tensor([[0.8010, 1.1935, 0.5948],
        [1.0067, 0.9957, 1.1292]])

In [0]:
#addition can also be done in multiple ways
x.add_(y)

tensor([[0.8010, 1.1935, 0.5948],
        [1.0067, 0.9957, 1.1292]])

In [0]:
torch.add(x,y)

tensor([[0.8278, 1.4789, 0.8825],
        [1.4387, 1.1272, 1.4161]])

In [0]:
torch.add(x,y, out=torch.empty(2,3))

tensor([[0.8278, 1.4789, 0.8825],
        [1.4387, 1.1272, 1.4161]])

In [0]:
# an '_' operator in any function used to replace any value previously assigned to a variable
x.add_(y)

tensor([[0.8278, 1.4789, 0.8825],
        [1.4387, 1.1272, 1.4161]])

In [0]:
x

tensor([[0.8278, 1.4789, 0.8825],
        [1.4387, 1.1272, 1.4161]])

In [0]:
# pytorch also support indexing and slicing like numpy
x[:,1]

tensor([1.4789, 1.1272])

In [0]:
# `view` is another command used to reshape a matrix or tensor 
x = torch.randn(4,5)
y = x.view(20)
z = x.view(-1,10)

In [0]:
print(x.size())
print(y.size())
print(z.size())

torch.Size([4, 5])
torch.Size([20])
torch.Size([2, 10])


In [0]:
# if a matrix is scalar, then its value can be accessed by `.items()`
x = torch.randn(1)
print(x)
x.item()

tensor([0.8015])


0.80146324634552

## Torch-2-Numpy

In [0]:
# torch tensor to numpy
x = torch.rand(5,5)
print(x)
x.numpy()

tensor([[0.1880, 0.5775, 0.8729, 0.6200, 0.9945],
        [0.1329, 0.3815, 0.8998, 0.8293, 0.5158],
        [0.1581, 0.2970, 0.0555, 0.4255, 0.3195],
        [0.3756, 0.3437, 0.1735, 0.8733, 0.5842],
        [0.3461, 0.9226, 0.0608, 0.6781, 0.6106]])


array([[0.18795717, 0.5774901 , 0.87294084, 0.6200417 , 0.99447906],
       [0.1329019 , 0.38150024, 0.8997833 , 0.8292822 , 0.515756  ],
       [0.15805984, 0.29701847, 0.05547643, 0.42554158, 0.3194772 ],
       [0.37559968, 0.34365302, 0.17349434, 0.873292  , 0.584156  ],
       [0.34606212, 0.9225988 , 0.06084901, 0.67813027, 0.61057097]],
      dtype=float32)

## Numpy-2-Torch

In [0]:
# numpy to torch tensor
import numpy as np
a = np.ones(10)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)


In [0]:
np.add(a,1, out=a)

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [0]:
a

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])